apiVersion: v2
appVersion: v2.3.0
description: A Helm chart for deploying the disaster recovery system components, including
  operator, server and web interface.
name: disaster-system
type: application
version: 2.3.0
