# Aliyun ACR image profile.
#
# Usage:
#   helm upgrade --install testudo . -n disaster-system --create-namespace -f values-aliyun.yaml

images:
  operator:
    repository: crpi-ftcmc8yukyvoj8qy.cn-hangzhou.personal.cr.aliyuncs.com/softcdata/testudo-operator
    tag: 1.0.1
    pullPolicy: IfNotPresent
  server:
    repository: crpi-ftcmc8yukyvoj8qy.cn-hangzhou.personal.cr.aliyuncs.com/softcdata/testudo-server
    tag: 1.0.1
    pullPolicy: IfNotPresent
  web:
    repository: crpi-ftcmc8yukyvoj8qy.cn-hangzhou.personal.cr.aliyuncs.com/softcdata/testudo-web
    tag: 1.0.1
    pullPolicy: IfNotPresent
