global:
  namespace: disaster-system

# 项目镜像统一配置
images:
  operator:
    repository: swr.cn-east-3.myhuaweicloud.com/chenmou/disaster-operator-arm64
    tag: v2.0.0
    pullPolicy: IfNotPresent
  server:
    repository: swr.cn-east-3.myhuaweicloud.com/chenmou/disaster-server
    tag: v2.0.0
    pullPolicy: IfNotPresent
  web:
    repository: swr.cn-east-3.myhuaweicloud.com/chenmou/disaster-web
    tag: v2.0.0
    pullPolicy: IfNotPresent

# Web 端专有配置
web:
  # 使用 K8s 内部 CoreDNS 名称，供 disaster-web 代理转发到 disaster-server
  backendUrl: "http://disaster-server:30081"
  service:
    type: NodePort
    port: 80
    nodePort: 30087

# Server 端专有配置（ClusterIP 仅集群内访问，由 web 代理对外提供服务）
server:
  service:
    type: ClusterIP
    port: 30081
