apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-controller-manager
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-leader-election-role
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-appbackup-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-appbackup-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-appbackup-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-apprestore-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-apprestore-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-apprestore-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - apprestores/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-backuppolicy-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-backuppolicy-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-backuppolicy-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - backuppolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-cluster-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-cluster-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-cluster-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - clusters/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterbackup-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterbackup-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterbackup-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterbackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterconfig-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterconfig-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterconfig-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterjob-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterjob-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterjob-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterjobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterpolicy-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterpolicy-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-disasterpolicy-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - disasterpolicies/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disaster-operator-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups
  - apprestores
  - backuppolicies
  - backuprestorestatisticses
  - clusters
  - datasyncs
  - disasterbackups
  - disasterconfigs
  - disasterdrills
  - disastergroups
  - disasterinstances
  - disasterjobs
  - disasteroperations
  - disasterpolicies
  - resourcesyncs
  - storagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups/finalizers
  - apprestores/finalizers
  - backuppolicies/finalizers
  - clusters/finalizers
  - datasyncs/finalizers
  - disasterbackups/finalizers
  - disasterconfigs/finalizers
  - disasterdrills/finalizers
  - disasterinstances/finalizers
  - disasterjobs/finalizers
  - disasteroperations/finalizers
  - disasterpolicies/finalizers
  - resourcesyncs/finalizers
  - storagerepositories/finalizers
  verbs:
  - update
- apiGroups:
  - testudo.softcdata.com
  resources:
  - appbackups/status
  - apprestores/status
  - backuppolicies/status
  - backuprestorestatisticses/status
  - clusters/status
  - datasyncs/status
  - disasterbackups/status
  - disasterconfigs/status
  - disasterdrills/status
  - disastergroups/status
  - disasterinstances/status
  - disasterjobs/status
  - disasteroperations/status
  - disasterpolicies/status
  - resourcesyncs/status
  - storagerepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disaster-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disaster-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-storagerepository-admin-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories
  verbs:
  - '*'
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-storagerepository-editor-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-storagerepository-viewer-role
rules:
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testudo.softcdata.com
  resources:
  - storagerepositories/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-leader-election-rolebinding
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: disaster-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: disaster-operator-controller-manager
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
  name: disaster-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: disaster-operator-manager-role
subjects:
- kind: ServiceAccount
  name: disaster-operator-controller-manager
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disaster-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: disaster-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: disaster-operator-controller-manager
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
    control-plane: controller-manager
  name: disaster-operator-controller-manager-metrics-service
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: disaster-operator
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-operator
    control-plane: controller-manager
  name: disaster-operator-controller-manager
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
spec:
  replicas: 1
  {{- with .Values.operator.strategy }}
  strategy:
{{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: disaster-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: disaster-operator
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        - name: {{ include "disaster-system.imagePullSecretName" . }}
      containers:
      - args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --health-probe-bind-address=:8081
        {{ if .Values.webhook.enabled }}
        - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        - --webhook-cert-name=tls.crt
        - --webhook-cert-key=tls.key
        {{ end }}
        command:
        - /app/manager
        env:
        - name: TZ
          value: {{ .Values.global.timezone | default "Asia/Shanghai" | quote }}
        image: {{ .Values.images.operator.repository }}:{{ .Values.images.operator.tag
          }}
        imagePullPolicy: {{ .Values.images.operator.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        {{ if .Values.webhook.enabled }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        {{ else }}
        ports: []
        {{ end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        {{ if .Values.webhook.enabled }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-server-cert
          readOnly: true
        {{ else }}
        volumeMounts: []
        {{ end }}
      serviceAccountName: disaster-operator-controller-manager
      terminationGracePeriodSeconds: 10
      {{ if .Values.webhook.enabled }}
      volumes:
      - name: webhook-server-cert
        secret:
          defaultMode: 420
          secretName: disaster-operator-webhook-server-cert
      {{ else }}
      volumes: []
      {{ end }}
