apiVersion: v1
kind: ConfigMap
metadata:
  name: disaster-platform-settings
  namespace: {{ .Values.global.namespace | default "disaster-system" }}
data:
  settings: '{"schemaVersion":1,"items":{"system.avatar":{"name":"Avatar","config_key":"system.avatar","value":"","remark":""},"system.title.en":{"name":"English title","config_key":"system.title.en","value":"Testudo","remark":""},"system.title.zh.cn":{"name":"Chinese title","config_key":"system.title.zh.cn","value":"Testudo","remark":""}},"updatedBy":"system"}'
